plugins {
    id 'java'
    id 'application'
}

group = 'ru.nsu.aeliseev2'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'ru.nsu.aeliseev2.taskj3.Application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}